/*
 * MainJFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package gui;

import javax.swing.ImageIcon;

import model.Adapter;

/**
 *
 * @author  __USER__
 */
public class MainJFrame extends javax.swing.JFrame {
	int count = 0, correctCount = 0, incorrectCount = 0;

	/** Creates new form MainJFrame */
	public MainJFrame() {
		initComponents();
		run();
	}

	public void run() {
		Adapter adapter = new Adapter();
		adapter.setUrlSrc(jTextField1.getText());
		adapter.run();
		jLabelImageOriginal.setIcon(new ImageIcon(adapter.getOriginalImage()));
		jLabelImageBinary.setIcon(new ImageIcon(adapter.getBinaryImage()));
		jLabelImageFixed.setIcon(new ImageIcon(adapter.getFixedImage()));
		if (adapter.isSuccess()) {
			jTextAreaImage1.setText(adapter.getResultImageContext(1));
			jTextAreaImage2.setText(adapter.getResultImageContext(2));
			jTextAreaImage3.setText(adapter.getResultImageContext(3));
			jTextAreaImage4.setText(adapter.getResultImageContext(4));
			jLabelResult.setText("<html><center>" + adapter.getResult()
					+ "</center></html>");
			String prob = "<html>";
			for (int which = 0; which <= 3; which++) {
				if (adapter.isSimilarityUnderLevel(which))
					prob += "<font color=red>" + adapter.getSimilarity(which)
							+ "</font>";
				else
					prob += adapter.getSimilarity(which);

				if (which < 3)
					prob += ",";
			}
			prob += "</html>";
			jLabelSimilarity.setText(prob);
			jButtonMatch.setEnabled(true);
		} else {
			String fail = "Fail";
			jTextAreaImage1.setText(fail);
			jTextAreaImage2.setText(fail);
			jTextAreaImage3.setText(fail);
			jTextAreaImage4.setText(fail);
			jLabelResult.setText(fail);
			jLabelSimilarity.setText(fail);
			jButtonMatch.setEnabled(false);
		}
		String stat = String.format("共测试%d次，识别成功%d次，失败%d次", count,
				correctCount, incorrectCount);
		jLabelStat.setText(stat);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabelImageOriginal = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabelImageBinary = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabelImageFixed = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		jLabelResult = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextAreaImage1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextAreaImage2 = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextAreaImage3 = new javax.swing.JTextArea();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextAreaImage4 = new javax.swing.JTextArea();
		jButtonRefresh = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		jLabelSimilarity = new javax.swing.JLabel();
		jLabelStat = new javax.swing.JLabel();
		jButtonMatch = new javax.swing.JButton();
		jButtonＮotMatch = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("pnju\u9a8c\u8bc1\u7801\u8bc6\u522b\u7cfb\u7edf - First Generation");

		jTextField1.setText("http://p.nju.edu.cn/img.html");

		jLabel1.setText("URL:");

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u539f\u59cb\u56fe\u50cf"));
		jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabelImageOriginal,
								javax.swing.GroupLayout.DEFAULT_SIZE, 130,
								Short.MAX_VALUE).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(
						jLabelImageOriginal,
						javax.swing.GroupLayout.PREFERRED_SIZE, 71,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		jPanel2.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u9ed1\u767d\u5316"));
		jPanel2.setPreferredSize(new java.awt.Dimension(100, 100));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabelImageBinary,
								javax.swing.GroupLayout.DEFAULT_SIZE, 130,
								Short.MAX_VALUE).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel2Layout.createSequentialGroup().addComponent(
						jLabelImageBinary,
						javax.swing.GroupLayout.DEFAULT_SIZE, 56,
						Short.MAX_VALUE).addContainerGap()));

		jPanel3.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u4fee\u6b63\u540e"));
		jPanel3.setPreferredSize(new java.awt.Dimension(100, 100));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabelImageFixed,
								javax.swing.GroupLayout.DEFAULT_SIZE, 130,
								Short.MAX_VALUE).addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel3Layout.createSequentialGroup().addComponent(
						jLabelImageFixed, javax.swing.GroupLayout.DEFAULT_SIZE,
						56, Short.MAX_VALUE).addContainerGap()));

		jPanel5.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u5224\u5b9a\u7ed3\u679c"));

		jLabelResult.setFont(new java.awt.Font("Courier New", 0, 36));

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel5Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabelResult,
								javax.swing.GroupLayout.DEFAULT_SIZE, 130,
								Short.MAX_VALUE).addContainerGap()));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel5Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabelResult,
								javax.swing.GroupLayout.DEFAULT_SIZE, 60,
								Short.MAX_VALUE).addContainerGap()));

		jPanel4.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u5206\u79bb"));

		jTextAreaImage1.setColumns(15);
		jTextAreaImage1.setFont(new java.awt.Font("Courier New", 0, 18));
		jTextAreaImage1.setRows(19);
		jScrollPane1.setViewportView(jTextAreaImage1);

		jTextAreaImage2.setColumns(15);
		jTextAreaImage2.setFont(new java.awt.Font("Courier New", 0, 18));
		jTextAreaImage2.setRows(19);
		jScrollPane2.setViewportView(jTextAreaImage2);

		jTextAreaImage3.setColumns(15);
		jTextAreaImage3.setFont(new java.awt.Font("Courier New", 0, 18));
		jTextAreaImage3.setRows(19);
		jScrollPane3.setViewportView(jTextAreaImage3);

		jTextAreaImage4.setColumns(15);
		jTextAreaImage4.setFont(new java.awt.Font("Courier New", 0, 18));
		jTextAreaImage4.setRows(19);
		jScrollPane4.setViewportView(jTextAreaImage4);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(30, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																jScrollPane4,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																438,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(97, Short.MAX_VALUE)));

		jButtonRefresh.setText("\u5237\u65b0");
		jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonRefreshActionPerformed(evt);
			}
		});

		jPanel6.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u7f6e\u4fe1\u6982\u7387"));

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel6Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabelSimilarity,
								javax.swing.GroupLayout.DEFAULT_SIZE, 130,
								Short.MAX_VALUE).addContainerGap()));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel6Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabelSimilarity,
								javax.swing.GroupLayout.DEFAULT_SIZE, 39,
								Short.MAX_VALUE).addContainerGap()));

		jLabelStat.setFont(new java.awt.Font("微软雅黑", 0, 18));
		jLabelStat.setText("\u7edf\u8ba1\u7ed3\u679c");

		jButtonMatch.setText("\u5339\u914d");
		jButtonMatch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonMatchActionPerformed(evt);
			}
		});

		jButtonＮotMatch.setText("\u4e0d\u5339\u914d");
		jButtonＮotMatch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonNotMatchActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				523,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jPanel6,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPanel1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								166,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPanel2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								166,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPanel3,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								166,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPanel5,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addGap(
																				29,
																				29,
																				29)
																		.addComponent(
																				jPanel4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				29,
																				29,
																				29)
																		.addComponent(
																				jLabelStat,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				504,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				61,
																				61,
																				61)
																		.addComponent(
																				jButtonMatch,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				78,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				28,
																				28,
																				28)
																		.addComponent(
																				jButtonＮotMatch,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				81,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				31,
																				31,
																				31)
																		.addComponent(
																				jButtonRefresh,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				77,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(35, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jPanel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				100,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jPanel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				29,
																				29,
																				29)
																		.addComponent(
																				jPanel3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				28,
																				28,
																				28)
																		.addComponent(
																				jPanel5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jPanel6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jButtonMatch)
																		.addComponent(
																				jButtonＮotMatch)
																		.addComponent(
																				jButtonRefresh))
														.addComponent(
																jLabelStat))
										.addContainerGap(45, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButtonNotMatchActionPerformed(java.awt.event.ActionEvent evt) {
		count++;
		incorrectCount++;
		run();
	}

	private void jButtonMatchActionPerformed(java.awt.event.ActionEvent evt) {
		count++;
		correctCount++;
		run();
	}

	private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {
		run();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainJFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButtonMatch;
	private javax.swing.JButton jButtonRefresh;
	private javax.swing.JButton jButtonＮotMatch;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelImageBinary;
	private javax.swing.JLabel jLabelImageFixed;
	private javax.swing.JLabel jLabelImageOriginal;
	private javax.swing.JLabel jLabelResult;
	private javax.swing.JLabel jLabelSimilarity;
	private javax.swing.JLabel jLabelStat;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTextArea jTextAreaImage1;
	private javax.swing.JTextArea jTextAreaImage2;
	private javax.swing.JTextArea jTextAreaImage3;
	private javax.swing.JTextArea jTextAreaImage4;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}